name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  PNPM_VERSION: 8.15.5

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
