name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

env:
  PNPM_VERSION: 6.32.9

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Run Tests
        run: pnpm run test:ember

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm run test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: 'test'
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          #- ember-release
          #- ember-beta
          #- ember-canary

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm exec ember try:one ${{ matrix.scenario }}
